# Generated by Django 5.1.3 on 2024-12-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
